# Vestigial boot entry — see 01-archiso-linux.conf for details.
# This efistub entry is unreachable at runtime since systemd-boot is not
# used, but archiso requires it for the uefi.systemd-boot buildmode.
title    Memtest86+
sort-key 03
efi      /boot/memtest86+/memtest.efi
architecture x64
