[sshd]
enabled      = true
port         = ssh
filter       = sshd
backend      = systemd
journalmatch = _SYSTEMD_UNIT=sshd.service + _COMM=sshd
maxretry     = 5
bantime      = 3600
findtime     = 600
